export default {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface": "#0b1326",
              "surface-dim": "#0b1326",
              "surface-bright": "#31394d",
              "surface-container-lowest": "#060e20",
              "surface-container-low": "#131b2e",
              "surface-container": "#171f33",
              "surface-container-high": "#222a3d",
              "surface-container-highest": "#2d3449",
              "on-surface": "#dae2fd",
              "on-surface-variant": "#c3c7cd",
              "outline": "#8d9197",
              "outline-variant": "#42474d",
              "primary": "#abcae8",
              "primary-container": "#3e5c76",
              "on-primary": "#12334b",
              "on-primary-container": "#b5d4f2",
              "secondary": "#adcebe",
              "secondary-container": "#2f4d40",
              "on-secondary-container": "#9cbcad",
              "tertiary": "#ecc15a",
              "error": "#ffb4ab",
              "background": "#0b1326",
            },
            fontFamily: {
              "headline-md": ["IBM Plex Serif", "serif"],
              "headline-sm": ["IBM Plex Serif", "serif"],
              "title-md": ["IBM Plex Sans Arabic", "sans-serif"],
              "title-sm": ["IBM Plex Sans Arabic", "sans-serif"],
              "body-md": ["IBM Plex Sans Arabic", "sans-serif"],
              "body-sm": ["IBM Plex Sans Arabic", "sans-serif"],
              "label-sm": ["JetBrains Mono", "monospace"],
              "label-md": ["JetBrains Mono", "monospace"],
              "data-metric": ["JetBrains Mono", "monospace"],
            },
            spacing: {
              "space-xs": "0.25rem",
              "space-sm": "0.5rem",
              "space-md": "1rem",
              "space-lg": "1.5rem",
              "space-xl": "2.5rem",
              "gutter-desktop": "1.5rem",
            },
          },
        },
 content: ["./index.html", "./src/**/*.{js,jsx}"],
};
